### ISSUE TITLE
Add VobSub support

### ISSUE THREAD

**Issue by Keith94** [Blitzker/assfiltermod#2]
Tested with: [Doremi].Hatsune.Miku.Magical.Mirai.2016.[SEGA].[1920x1080].[Blu-ray].[8-bit].[0D860401].mkv

assfiltermod_harfbuzz_x3_x64 => Video loads but all subtitle tracks (including .ass) don't display

assfiltermod_harfbuzz_x4_x64 => madVR crashes when opening the file: `Zugriffsverletzung bei Adresse $7f87c6c70c6 in Modul 'assfiltermod.dll'. Lesen von Adresse $70.`

**Comment by Blitzker** [comment]
Please test with the latest release. This should be fixed.

**Comment by Keith94** [comment]
I confirm it's fixed in 0.3. Will VOBSUB or HDMVSUB ever be supported?

**Comment by Blitzker** [comment]
Good, thanks for testing.

As for VOBSUB & PGS, i would like to eventually implement them but the problem is that there is no lightweight library (like libass) that support them. So porting the code from VSFilter would be the logical solution but its a lot of work.

I don't say i won't do it but i can't confirm it either.

**Comment by Keith94** [comment]
OK - thanks for reply.

**Comment by amayra** [comment]
@Blitzker you can use VobSub/PGS code from MPC-HC or MPC-BE like @clsid said if i have free time i will help you with this

**Comment by amayra** [comment]
bytheway there difference between MPC-HC ISR and MPC-BE ISR 
you should keep this in your mind
